#!/bin/bash

sudo xbps-install -S void-repo-multilib void-repo-nonfree void-repo-multilib-nonfree

sudo xbps-install -S neovim git make gcc libX11-devel nvidia nvidia-libs-32bit libgcc-32bit libdrm-32bit libglvnd-32bit libstdc++-32bit libXft-devel libXinerama-devel zsh zathura-pdf-mupdf xtools xrandr xprop xclip xcalc unzip transmission-gtk tar steam terminus-font shotcut shotwell scrot ranger rofi qalculate picom pavucontrol pamixer pango obs numlockx noto-fonts-emoji nitrogen neovim neofetch nautilus mpv mlocate lxappearance lm_sensors libxcvt libxcb leafpad go gnome-screenshot font-inconsolata-otf flatpak firefox feh expat dunst dejavu-fonts-ttf dbus curl cargo btop awesome alsa-tools alsa-utils alsa-plugins-pulseaudio alacritty 
